name: Partial Repository Clone

on:
  workflow_dispatch:  # 保留手动触发选项
  push:
    paths:
      - 'scripts/**'  # 当 scripts 目录下的文件发生变化时触发
      - 'config.yml'  # 当 config.yml 文件发生变化时触发
  pull_request:
    paths:
      - 'scripts/**'  # 当 PR 中 scripts 目录下的文件发生变化时触发
      - 'config.yml'  # 当 PR 中 config.yml 文件发生变化时触发

# 添加权限配置
permissions:
  contents: write  # 允许修改仓库内容
  pull-requests: write  # 如果需要创建 PR，可以添加此权限

jobs:
  partial-clone:
    runs-on: ubuntu-latest
    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      
      - name: 设置 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
      
      - name: 设置 GitHub CLI 和 Git 认证
        run: |
          # GitHub Actions runner 已预装 GitHub CLI
          # 使用 GITHUB_TOKEN 进行身份验证
          echo "${{ github.token }}" | gh auth login --with-token
          # 配置 Git 使用 GitHub CLI 的认证
          gh auth setup-git
      
      - name: 执行部分克隆
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # 确保脚本可执行
          chmod +x ./scripts/partial_clone.py
          # 执行脚本
          python ./scripts/partial_clone.py
